version: '3.5'
services:
  server:
    build:
      context: ./back
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    volumes:
      - ./back:/app
    networks:
      - main
    restart: always
  client_mobile:
    build:
      context: './Appli'
  client_web:
    depends_on:
      - "server"
      - "client_mobile"
    build:
      context: ./area-web-app
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - API_IP=server
    volumes:
      - ./area-web-app:/app
    networks:
      - main
    restart: always

networks:
  main:
